export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOAD_USER_DATA = "LOAD_USER_DATA";
export const LOAD_USER_DATA_FAIL = "LOAD_USER_DATA_FAIL";
export const LOAD_USER_DATA_SUCCESS = "LOAD_USER_DATA_SUCCESS";
